[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solyx = "BpiRoot4rW4WaTdVQEpudG2RhQe3geXx7toBGPJRmb9j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./config/wallet_id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
dev = "cd ./app && bun run dev"
gen_kp = "bun run write_keypair.ts"
