[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solyx = "H33Yw4gvdMANdvTVtz7mLXAstmokScAHQmLuUGvESWEG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./config/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
